rm(list = ls())
library("dplyr")
library("leaflet")
library("shiny")
library("ggplot2")
library("plotly")
library("tidyverse")
source("my_server.R")
source("my_ui.R")

options(shiny.trace = F)
shinyApp(ui = my_ui, server = my_server)
